name: ステップ 0, ようこそ

# このステップは、学習者がテンプレートから新しいリポジトリを作成した後にトリガーされます。
# このワークフローは、ステップ 0 からステップ 1 に更新します。

# これは、`main` にコミットをプッシュするたびに実行されます。
# 参考: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

# 参考: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # リポジトリをチェックアウトするには `contents: read` が必要です。
  # ステップのメタデータを更新するには `contents: write` が必要です。
  contents: write

jobs:
  # 学習者が同じステップにいる場合にのみ、メインジョブを実行するために現在のステップを取得します。
  get_current_step:
    name: 現在のステップ番号を確認
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_welcome:
    name: ようこそ
    needs: get_current_step

    # このアクションは、以下の場合にのみ実行されます。
    # 1. このリポジトリがテンプレートリポジトリではない。
    # 2. 現在のステップが 0 である。
    # 参考: https://docs.github.com/en/actions/learn-github-actions/contexts
    # 参考: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 0 }}

    # Mac または Windows の代わりに、パフォーマンスのために Ubuntu を実行します。
    runs-on: ubuntu-latest

    steps:
      # README.md を編集できるように、リポジトリをチェックアウトする必要があります。
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # すべてのブランチを取得しましょう。

      # README.md で、ステップ 0 をステップ 1 に切り替えます。
      - name: ステップ 1 に更新
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          branch_name: my-first-branch
