name: ステップ 1, ブランチを作成

# このステップは、学習者がブランチ `my-first-branch` を作成するのを待ちます。
# このワークフローは、ステップ 1 からステップ 2 に更新されます。

# これは、ブランチまたはタグを作成するたびに実行されます。
# 参照: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  create:

# 参照: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # リポジトリをチェックアウトするには `contents: read` が必要です。
  # ステップのメタデータを更新するには `contents: write` が必要です。
  contents: write

jobs:
  # 現在のステップを取得して、学習者が同じステップにいる場合にのみメインジョブを実行します。
  get_current_step:
    name: 現在のステップ番号を確認
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_create_a_branch:
    name: ブランチ作成時
    needs: get_current_step

    # これは以下の場合にのみ実行されます:
    # 1. このリポジトリがテンプレートリポジトリではない。
    # 2. 現在のステップが 1 である。
    # 3. イベントがブランチである。
    # 4. ブランチ名が `my-first-branch` である。
    # 参照: https://docs.github.com/en/actions/learn-github-actions/contexts
    # 参照: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 1
          && github.ref_type == 'branch'
          && github.ref_name == 'my-first-branch' }}

    # Mac または Windows ではなく、パフォーマンスのために Ubuntu を実行します。
    runs-on: ubuntu-latest

    steps:
      # README を編集できるように、リポジトリをチェックアウトする必要があります。
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # すべてのブランチを取得しましょう。

      # README.md で、ステップ 1 をステップ 2 に切り替えます。
      - name: ステップ 2 に更新
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: my-first-branch
